### ISSUE TITLE
How to load and process with my own datasets

### ISSUE THREAD

**Issue by codaibk** [google-research/federated#22]
Hi,
In this framework, you use some available dataset from TFF (example: tff.simulation.datasets.emnist.load_data()). I am wondering how I can deal with my own dataset for image classification task. My dataset includes image and label. cCuld you please give me the hint how to convert my dataset into your input data format or how I can modify the your code corresponding to my own dataset?.
Thanks.

**Comment by ZacharyGarrett** [comment]
The [[tesnorflow_federated] StackOverflow tag](https://stackoverflow.com/questions/tagged/tensorflow-federated) is generally a better place for questions of "how to", whereas GitHub Issues are used to deal with bugs/bad behaviors in the code.

Some related questions that might help, otherwise try starting a new question:

- [How define tff.simulation.ClientData.from_clients_and_fn Function?](https://stackoverflow.com/questions/60265798/tff-how-define-tff-simulation-clientdata-from-clients-and-fn-function)
- [How to create federated dataset from a CSV file?](https://stackoverflow.com/questions/58965488/how-to-create-federated-dataset-from-a-csv-file)
- [convert my own image dataset into tff simulation Clientdata](https://stackoverflow.com/questions/59741397/federated-learning-convert-my-own-image-dataset-into-tff-simulation-clientdata)
